# Generated by Django 3.1.2 on 2020-10-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='tokken',
        ),
        migrations.AddField(
            model_name='myuser',
            name='otp',
            field=models.CharField(default=56060, max_length=6),
        ),
    ]
