# Generated by Django 3.1.2 on 2020-10-18 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_capital', models.DecimalField(decimal_places=1, default=0, max_digits=500000)),
            ],
        ),
        migrations.CreateModel(
            name='Unpaid_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_merged', models.DecimalField(decimal_places=1, default=0, max_digits=500000)),
                ('merged_to_pay', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('capital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital', to='tradeapp.capital')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paid_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('recieving_amount', models.DecimalField(decimal_places=1, default=0, max_digits=500000)),
                ('recieved_amount', models.DecimalField(decimal_places=1, default=0, max_digits=500000)),
                ('receiving_from', models.CharField(blank=True, max_length=200, null=True)),
                ('merged_to_receive', models.BooleanField(default=False)),
                ('amount_received', models.DecimalField(decimal_places=1, default=0, max_digits=500000)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
