# Generated by Django 3.1.2 on 2020-10-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0004_auto_20201018_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='unpaid_user',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=500000),
        ),
    ]
