# Generated by Django 3.1.2 on 2020-10-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0007_auto_20201018_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paid_user',
            old_name='amount_received',
            new_name='amount_merged',
        ),
        migrations.RenameField(
            model_name='paid_user',
            old_name='recieving_amount',
            new_name='mamount_to_receive',
        ),
        migrations.RemoveField(
            model_name='paid_user',
            name='merged_to_pay',
        ),
    ]
