# Generated by Django 3.1.2 on 2020-10-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0008_auto_20201018_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paid_user',
            old_name='mamount_to_receive',
            new_name='amount_to_receive',
        ),
    ]
