# Generated by Django 3.0.8 on 2020-10-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0033_auto_20201009_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='device_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
