# Generated by Django 3.1.2 on 2020-10-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0002_auto_20201018_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid_user',
            name='user_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='unpaid_user',
            name='account_paying_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
