# Generated by Django 3.1.2 on 2020-10-18 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tradeapp', '0003_auto_20201018_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unpaid_user',
            name='capital',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=500000),
        ),
    ]
