# Generated by Django 3.1.2 on 2020-10-20 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tradeapp', '0009_auto_20201018_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unpaid_user',
            options={'ordering': ['date_join']},
        ),
        migrations.RenameField(
            model_name='paid_user',
            old_name='amount_to_receive',
            new_name='amount_to_merge',
        ),
        migrations.RenameField(
            model_name='paid_user',
            old_name='merged_completed',
            new_name='received_completed',
        ),
        migrations.RemoveField(
            model_name='paid_user',
            name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='unpaid_user',
            name='merged_completed',
        ),
        migrations.AddField(
            model_name='paid_user',
            name='amount_received',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=500000),
        ),
        migrations.AddField(
            model_name='unpaid_user',
            name='amount_payed',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=500000),
        ),
        migrations.AddField(
            model_name='unpaid_user',
            name='date_join',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='capital',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paid_user',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unpaid_user',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivers_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=500000)),
                ('account_paying_to', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_capital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradeapp.unpaid_user')),
            ],
        ),
    ]
