# Generated by Django 3.1.2 on 2020-10-20 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0010_auto_20201020_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unpaid_user',
            name='capital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradeapp.capital'),
        ),
    ]
