# Generated by Django 3.1.2 on 2020-10-20 22:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0001_initial'),
        ('tradeapp', '0012_auto_20201020_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payer_transaction_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Receivers_transaction_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradeapp.unpaid_user')),
            ],
        ),
        migrations.AlterField(
            model_name='paid_user',
            name='user_account_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userwallet.userwallet'),
        ),
        migrations.DeleteModel(
            name='PTransaction',
        ),
        migrations.AddField(
            model_name='receivers_transaction_table',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradeapp.paid_user'),
        ),
        migrations.AddField(
            model_name='payer_transaction_table',
            name='receiver_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradeapp.paid_user'),
        ),
        migrations.AddField(
            model_name='payer_transaction_table',
            name='user_capital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradeapp.unpaid_user'),
        ),
    ]
