# Generated by Django 3.1.2 on 2020-10-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0013_auto_20201020_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unpaid_user',
            name='account_paying_to',
        ),
        migrations.AddField(
            model_name='payer_transaction_table',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=500000),
        ),
        migrations.AddField(
            model_name='receivers_transaction_table',
            name='amount_to_receive',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=500000),
        ),
    ]
