# Generated by Django 3.1.2 on 2020-10-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0014_auto_20201020_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paid_user',
            name='receiving_from',
        ),
    ]
