# Generated by Django 3.1.2 on 2020-10-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0015_remove_paid_user_receiving_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payer_transaction_table',
            old_name='user_capital',
            new_name='user',
        ),
    ]
