# Generated by Django 3.1.2 on 2020-10-21 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0016_auto_20201020_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivers_transaction_table',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receivers_transaction_table',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
