# Generated by Django 3.1.2 on 2020-10-21 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0017_auto_20201021_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payer_transaction_table',
            old_name='user',
            new_name='payer_details',
        ),
        migrations.RenameField(
            model_name='receivers_transaction_table',
            old_name='user',
            new_name='receiver_details',
        ),
    ]
