# Generated by Django 3.1.2 on 2020-10-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0004_auto_20201020_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='user_account_number',
            field=models.IntegerField(default='7713454479'),
        ),
    ]
